language: python
python:
  - "2.7"
branches:
  only:
  - pelican
before_install:
- openssl aes-256-cbc -K $encrypted_0c1ea85c4016_key -iv $encrypted_0c1ea85c4016_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:WorkShopLinux/WorkShopLinux.github.io.git
- git fetch origin -f master:master
#install:
#
#- pip install tox
#script:
#    tox -e travis
#- make github

install:
- pip install --upgrade pip
- pip install markdown
- pip install beautifulsoup4
- pip install typogrify
- pip install remarkable
- pip install pelican
- pip install ghp-import
script:
- make github
